[versions]
agp = "8.3.1"
kotlin = "1.9.0"
coreKtx = "1.12.0"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
lifecycleRuntimeKtx = "2.7.0"
activityCompose = "1.8.2"
composeBom = "2023.08.00"
roomVersion = "2.6.1"
copmpilerKspVersion = "1.9.21-1.0.15"
datastoreVersion = "1.0.0"
viewmodelVersion = "2.7.0"
navigationlVersion = "2.7.7"
hiltVersion = "1.2.0"
daggerVersion = "2.49"
material = "1.6.5"

[libraries]
androidx-room = { group = "androidx.room", name = "room-ktx", version.ref = "roomVersion" }
androidx-room-ksp = { group = "androidx.room", name = "room-compiler", version.ref = "roomVersion" }
androidx-datastore= { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastoreVersion" }
androidx-viewmodel= { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "viewmodelVersion" }
androidx-navigation= { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationlVersion" }
androidx-material={group = "androidx.compose.material", name = "material", version.ref = "material"}

androidx-hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "daggerVersion" }
androidx-hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "daggerVersion" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltVersion" }
androidx-hilt-navigation-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hiltVersion" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compilerKsp = { id = "com.google.devtools.ksp", version.ref = "copmpilerKspVersion" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "daggerVersion" }
